version: '3'

services:
    jekyll:
        image: jekyll/minimal:4
        volumes:
          - ./:/srv/jekyll:delegated
          - ./vendor/bundle:/usr/local/bundle
        ports:
          - 4000:4000
        command: jekyll serve --watch --force_polling
