version: '3'

services:
    jekyll:
        image: jekyll/jekyll:4
        volumes:
          - ./:/srv/jekyll:delegated
          - ./vendor/bundle:/usr/local/bundle
        ports:
          - '4000:4000'
        command: >
            bash -c "
                bundle install &&
                bundle exec jekyll serve --watch --force_polling --incremental -H 0.0.0.0
            "
